version: "3.7"

networks:
    daiquiri_net:
        ipam:
            driver: default
            config:
                - subnet: 172.22.22.0/28

volumes:
    log:
        name: <GLOBAL_PREFIX>log
        driver_opts:
            type: none
            device: <CURDIR>/vol/log
            o: bind
    download:
        name: <GLOBAL_PREFIX>download
        driver_opts:
            type: none
            device: <CURDIR>/vol/download
            o: bind
    files:
        name: <GLOBAL_PREFIX>files
        driver_opts:
            type: none
            device: <CURDIR>/vol/files
            o: bind
    postgresapp:
        name: <GLOBAL_PREFIX>postgresapp
        driver_opts:
            type: none
            device: <CURDIR>/vol/postgres-app
            o: bind
    postgresdata:
         name: <GLOBAL_PREFIX>postgresdata
         driver_opts:
            type: none
            device: <CURDIR>/vol/postgres-data
            o: bind
    daiquiri:
        name: <GLOBAL_PREFIX>daiquiri
        driver_opts:
            type: none
            device: <CURDIR>/vol/daiquiri
            o: bind
    ve:
        name: <GLOBAL_PREFIX>ve
        driver_opts:
            type: none
            device: <CURDIR>/vol/ve
            o: bind
    wp:
        name: <GLOBAL_PREFIX>wp
        driver_opts:
            type: none
            device: <CURDIR>/vol/wp
            o: bind

    wpdb:
        name: <GLOBAL_PREFIX>wpdb
        driver_opts:
            type: none
            device: <CURDIR>/vol/wpdb
            o: bind

services:
    daiquiri:
        build:
            context: ./daiquiri
        container_name: <GLOBAL_PREFIX>daiquiri
        depends_on:
            - postgresapp
        links:
            - postgresdata
            - wpdb
        ports:
            - "<FINALLY_EXPOSED_PORT>:80"
        volumes:
            - log:/vol/log
            - download:/vol/download
            - files:/vol/files
            - daiquiri:/vol/daiquiri
            - ve:/vol/ve
            - wp:/vol/wp
        restart: always
        env_file:
            - <VARIABLES_FILE>
        networks:
            daiquiri_net:
                ipv4_address: 172.22.22.11

    postgresapp:
        build:
            context: ./postgresapp
        container_name: <GLOBAL_PREFIX>postgresapp
        volumes:
            - postgresapp:/var/lib/postgresql/data
        restart: always
        env_file:
            - <VARIABLES_DB_APP>
        networks:
            daiquiri_net:
                ipv4_address: 172.22.22.12

    postgresdata:
        build:
            context: ./postgresdata
        container_name: <GLOBAL_PREFIX>postgresdata
        volumes:
            - postgresdata:/var/lib/postgresql/data
        restart: always
        env_file:
            - <VARIABLES_DB_DATA>
        networks:
            daiquiri_net:
                ipv4_address: 172.22.22.13


    wpdb:
        image: mysql:5.7
        container_name: <GLOBAL_PREFIX>wpdb
        volumes:
            - wpdb:/var/lib/mysql
        restart: always
        env_file:
            - <VARIABLES_WP>
        networks:
            daiquiri_net:
                ipv4_address: 172.22.22.14
