version: "3.7"

volumes:
    log:
        name: <GLOBAL_PREFIX>log
        driver_opts:
            type: none
            device: <CURDIR>/vol/log
            o: bind
    download:
        name: <GLOBAL_PREFIX>download
        driver_opts:
            type: none
            device: <CURDIR>/vol/download
            o: bind
    postgresapp:
        name: <GLOBAL_PREFIX>postgresapp
        driver_opts:
            type: none
            device: <CURDIR>/vol/postgres-app
            o: bind
    postgresdata:
         name: <GLOBAL_PREFIX>postgresdata
         driver_opts:
            type: none
            device: <CURDIR>/vol/postgres-data
            o: bind
    daiquiri:
        name: <GLOBAL_PREFIX>daiquiri
        driver_opts:
            type: none
            device: <CURDIR>/vol/daiquiri
            o: bind
    ve:
        name: <GLOBAL_PREFIX>ve
        driver_opts:
            type: none
            device: <CURDIR>/vol/ve
            o: bind
    wp:
        name: <GLOBAL_PREFIX>wp
        driver_opts:
            type: none
            device: <CURDIR>/vol/wp
            o: bind

    wpdb:
        name: <GLOBAL_PREFIX>wpdb
        driver_opts:
            type: none
            device: <CURDIR>/vol/wpdb
            o: bind

services:
    nginx:
        build:
            context: ./nginx
        container_name: <GLOBAL_PREFIX>nginx
        ports:
            - "<FINALLY_EXPOSED_PORT>:80"
        links:
            - daiquiri
            - wp
        volumes:
            - daiquiri:/vol/daiquiri
            - ve:/vol/ve
            - log:/vol/log
        restart: always
        env_file:
            - <VARIABLES_FILE>

    postgresapp:
        build:
            context: ./postgresapp
        container_name: <GLOBAL_PREFIX>postgresapp
        volumes:
            - postgresapp:/var/lib/postgresql/data
        restart: always
        env_file:
            - <VARIABLES_DB_APP>

    postgresdata:
        build:
            context: ./postgresdata
        container_name: <GLOBAL_PREFIX>postgresdata
        volumes:
            - postgresdata:/var/lib/postgresql/data
        restart: always
        env_file:
            - <VARIABLES_DB_DATA>

    daiquiri:
        build:
            context: ./daiquiri
        container_name: <GLOBAL_PREFIX>daiquiri
        depends_on:
            - postgresapp
        links: 
            - postgresdata
        expose:
            - "9001"
        volumes:
            - log:/vol/log
            - download:<DOWNLOAD_DIR>
            - daiquiri:/vol/daiquiri
            - ve:/vol/ve
            - wp:/var/www/html/wordpress
        restart: always
        env_file:
            - <VARIABLES_FILE>

    wpdb:
        image: mysql:5.7
        container_name: <GLOBAL_PREFIX>wpdb
        volumes:
            - wpdb:/var/lib/mysql
        restart: always
        env_file:
            - <VARIABLES_WP>

    wp:
        build: 
            context: ./wordpress 
        container_name: <GLOBAL_PREFIX>wp
        links:
            - wpdb
        volumes:
            - wp:/var/www/html/wordpress
            - log:/vol/log
        restart: always
        env_file:
           - <VARIABLES_WP>
        