version: "3.7"

volumes:
    log: 
      name: log
      driver_opts:
          type: none
          device: /home/galkin/code/django-daiquiri/docker-compose/vol/log
          o: bind
    wp:
      name: wp
      driver_opts:
          type: none
          device: /home/galkin/code/django-daiquiri/docker-compose/vol/wp
          o: bind

    wpdb:
      name: wpdb
      driver_opts:
          type: none
          device: /home/galkin/code/django-daiquiri/docker-compose/vol/wpdb
          o: bind

services:    
    wpdb:
        image: mysql:5.7
        container_name: dq-wpdb
        volumes:
            - log:/vol/log
            - wpdb:/var/lib/mysql
        env_file:
            - settings/wp.env

    wp:
        build: 
            context: ./wordpress
        container_name: dq-wp
        restart: always
        depends_on:
            - wpdb
        volumes:
            - log:/vol/log
            - wp:/var/www/html/wordpress
        env_file:
            - settings/wp.env
    
    nginx:
        build:
            context: ./nginx
        container_name: dq-nginx
        links:
            - wp
        restart: always
        ports:
            - "8080:80"
        volumes:
            - log:/vol/log