FROM debian:latest

ENV PATH=/opt:${PATH}

RUN apt update -y && apt install -y \
    python3 \
    python3-dev \
    python3-pip \
 && pip3 install virtualenv

# build dependencies
RUN apt install -y \
    build-essential \
    curl \
    git \
    libxml2-dev \
    libxslt-dev \
    zlib1g-dev \
    make \
    vim

# postgres client
RUN apt install -y \
    libpq-dev \
    postgresql \
    postgresql-client \
    python-psycopg2

COPY ./rootfs /

RUN useradd -ms /bin/bash daiquiri
RUN chmod a+x /drun.sh
USER daiquiri

CMD ["/drun.sh"]
