FROM centos:latest

ENV PATH=/vol/ve/bin:/opt:${PATH} 

RUN yum update -y && yum install -y \
    yum-utils \
    epel-release \
    wget

RUN yum makecache

RUN yum install -y \
    python36 \
    python36-devel \
    python36-pip 

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade virtualenv 

RUN yum install -y\
    build-essential \
    gcc \
    curl \
    git \
    make \
    vim \
    libpq-dev \
    glibc-devel \
    postgresql-libs \
    postgresql-devel \
    python36-psycopg2 \
    wp-cli

# update php to 7.3
RUN wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
     rpm -Uvh remi-release-7.rpm && \
     yum-config-manager --enable remi-php73 && \
     yum update -y && \ 
     yum install -y php-mysql
    
RUN pip3 install gunicorn

COPY ./rootfs /

RUN useradd -ms /bin/bash daiquiri
RUN chown -R daiquiri.daiquiri /home/daiquiri
# USER daiquiri

CMD ["/drun.sh"]
