FROM centos:latest

RUN yum update -y && yum install -y \
   yum-utils \
   epel-release

RUN yum makecache

RUN yum install -y \
   nginx \
   curl

RUN mkdir -p /etc/nginx/conf.d
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/vhost.conf /etc/nginx/conf.d/vhost.conf

COPY ./drun.sh /

RUN useradd -ms /bin/bash daiquiri

HEALTHCHECK --timeout=10s --interval=20s --retries=3 \
   CMD curl -f http://localhost:80 || exit 1

# CMD ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
CMD ["/drun.sh"]