FROM wordpress

RUN apt-get update && \ 
       apt-get install -y --no-install-recommends git 

COPY ./rootfs /

RUN a2enmod remoteip && \
       a2dissite 000-default && \ 
       a2ensite vhost
       
CMD ["/drun.sh"]


