FROM wordpress

RUN apt-get update && \ 
       apt-get install -y --no-install-recommends git vim

COPY ./rootfs /

# enable apache mods and set vhost conf
RUN a2enmod remoteip rewrite proxy proxy_http && \
       a2dissite 000-default && \ 
       a2ensite vhost 
       
CMD ["/drun.sh"]


